services:
  db:
    image: postgres:17
    container_name: db_app
    command: -p 1221
    expose:
      - "1221"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-p", "1221"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - "5370"
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "5370", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "9999:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
