"""Fix default values for timestamps

Revision ID: 1873946ab4e6
Revises: 5113665c6d53
Create Date: 2025-03-29 17:14:21.032938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision: str = '1873946ab4e6'
down_revision: Union[str, None] = '5113665c6d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'links', 'created_at',
        server_default=func.now(),
        existing_type=sa.TIMESTAMP(timezone=True),
        nullable=False
    )
    op.alter_column(
        'redirects', 'timestamp',
        server_default=func.now(),
        existing_type=sa.TIMESTAMP(timezone=True),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'links', 'created_at',
        server_default=None,
        existing_type=sa.TIMESTAMP(timezone=True),
        nullable=False
    )
    op.alter_column(
        'redirects', 'timestamp',
        server_default=None,
        existing_type=sa.TIMESTAMP(timezone=True),
        nullable=False
    )
    # ### end Alembic commands ###
